version: '3.1'
services:
  app:
    build: .
    ports:
     - "3000:3000"
    environment:
     - MYSQL_HOST='localhost'
     - MYSQL_USER='root'
     - MYSQL_PASSWORD=''
     - MYSQL_DATABASE='zoo'
     - MYSQL_PORT='3306'
    image: "arturotucan/webrepo:app"